apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-service
spec:
  selector:
    app: employee-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
