apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-service
spec:
  selector:
    app: employee-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer
