apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend

    spec:
      containers:
        - name: employee-frontend

          image: dustinyansberg/employee-frontend:latest

          ports:
            - containerPort: 4200
